# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'DevOpsDemo/DevOpsDemo/*.csproj'
    feedsToUse: 'select'
    vstsFeed: '180b9bd8-aeb8-46b7-849d-c6ad8889fc2e'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    workingDirectory: 'DevOpsDemo'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'DevOpsDemo/DevOpsDemo.Tests/DevOpsDemo.Tests.csproj'
    testRunTitle: 'Running DevOpsDemo.Tests'