# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $url = 'https://objectivec2swift.com/#/converter/'
      try {
          Write-Host "Running Health Check..."
          $res = Invoke-WebRequest -Uri $url
          if($res.StatusCode -eq 200)
          {
              Write-Host "$url is alive"
          }
          else
          {
              Write-Host "Wrong Status Code: " $res.StatusCode
              Write-Host $res
              exit 1;
          }
      } 
      catch [System.Exception] {
          Write-Host "Exception block"
          $res = $_.Exception
          Write-Host $res;
          exit 1;
      }

  
